python3 main_continual.py \
    --dataset imagenet100 \
    --encoder resnet18 \
    --data_dir /home/sol-ex-inanis/Data/ \
    --train_dir tiny-imagenet-200/train \
    --val_dir tiny-imagenet-200/val \
    --split_strategy class \
    --max_epochs 500 \
    --num_tasks 10 \
    --task_idx 1 \
    --gpus 0 \
    --num_workers 5 \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.4 \
    --weight_decay 1e-4 \
    --batch_size 256 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 1.0 0.1 \
    --solarization_prob 0.0 0.2 \
    --name barlow-imagenet100-10T \
    --save_checkpoint \
    --entity unitn-mhug \
    --project ever-learn \
    --scale_loss 0.1 \
    --method barlow_twins \
    --proj_hidden_dim 2048 \
    --output_dim 2048 \
    --scale_loss 0.1 \
    --distiller decorrelative \
    --pretrained_model None \